[package]
name = "nem"
version = "0.0.1"
authors = ["Lee Olayvar <leeola@fastmail.com>"]
edition = "2018"

[features]
default = ["server"]
server = ["nem_server"]

[dependencies]
# Feature deps
nem_server = { path = "../server", optional = true }
