[package]
name = "nem_server"
version = "0.0.1"
authors = ["Lee Olayvar <leeola@fastmail.com>"]
edition = "2018"

[dependencies]
axum = "0.3.0"
hyper = "0.14.14"
tower = "0.4.10"
tower-http = "0.1.1"
