[package]
name = "nem_server"
version = "0.0.1"
authors = ["Lee Olayvar <leeola@fastmail.com>"]
edition = "2018"

[dependencies]
axum = { version = "0.4", features = ["ws"] }
hyper = "0.14"
tower = "0.4"
tower-http = "0.2"
serde = { version = "1.0", features = ["derive"] }
