[package]
name = "nem_gui_dom"
version = "0.1.0"
edition = "2021"

[lib]
name = "nem_gui_dom"
path = "src/lib.rs"

[[bin]]
name = "nem-gui-dom"
path = "src/main.rs"

[dependencies]
sycamore = "0.7.1"

