[package]
publish = false
name = "mnemosyne-make"
description = "a build helper for nem crates"
version = "0.1.0"
authors = ["Lee Olayvar <leeola@fastmail.com>"]
edition = "2018"

[dependencies]
wasm-pack = "0.8.1"
structopt = "0.3.9"
log = "0.4.8"
